# k8s/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msc-bcp-register-api
  labels:
    app: msc-bcp-register-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msc-bcp-register-api
  template:
    metadata:
      labels:
        app: msc-bcp-register-api
    spec:
      containers:
        - name: msc-bcp-register-api
          image: msc-bcp-register-api:latest  # Replace with the actual image repository and tag
          ports:
            - containerPort: 3000

      imagePullSecrets:
        - name: ghcr-secret  # Referencing the secret created for GHCR access

