apiVersion: apps/v1
kind: Deployment
metadata:
  name: msc-bcp-register-api
  namespace: bcp-dev
  labels:
    app: msc-bcp-register-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msc-bcp-register-api
  template:
    metadata:
      labels:
        app: msc-bcp-register-api
    spec:
      containers:
      - name: msc-bcp-register-api
        image: ghcr.io/gobamm/msc-bcp-register-api:latest
        ports:
            - containerPort: 3000
