apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: msc-bcp-register-api
        image: ghcr.io/gobamm/msc-bcp-register-api:dev
