# k8s/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: bcp-register  
  name: msc-bcp-register-api
  labels:
    app: msc-bcp-register-api
spec:
  type: LoadBalancer
  selector:
    app: msc-bcp-register-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
