# k8s/overlays/dev/deployment-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msc-bcp-register-api  # Must match the name in the base deployment.yaml
spec:
  replicas: 1  # Reduce replicas for the dev environment  
  template:
    spec:
      containers:
        - name: msc-bcp-register-api
          image: msc-bcp-register-api:latest  # Use a development-specific image tag

