name: Build & Deploy bcp-register-api

on:
  workflow_dispatch:
  #push:
  #  branches: [ "develop" ]

  #pull_request:
  #  branches: ["release", "main","develop"]
     
  #release:
  #  types: [published] # Trigger on tag-based pull request to main branch


permissions:
   id-token: write
   contents: read
   actions: read

jobs:

  sast:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check Event Scope
      run: |
        echo "Triggered by tag: $GITHUB_REF_NAME"
        echo "Tag Ref Name: $GITHUB_REF"
        echo "Event Name: $GITHUB_EVENT_NAME"
        echo "Base Ref: ${{ github.base_ref }}"

    - name: Run Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_PYTHON: true
        FILTER_REGEX_INCLUDE: .*\.(py)$
        GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
        LOG_FILE: /tmp/super-linter.log  # Specify the log file location        
      continue-on-error: true

    - name: Upload Linter Results
      uses: actions/upload-artifact@v3
      with:
        name: linter-results
        path: /tmp/super-linter.log
    
    - name: Run Unit Tests
      run: |
        pip install pytest pytest-cov 
        pytest --cov=src tests/
      continue-on-error: true

      
    # Set up Java (required for SonarQube Scanner)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    # Cache SonarQube scanner
    - name: Cache SonarQube scanner
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-cache
        restore-keys: |
          ${{ runner.os }}-sonar-cache

    # Download and install SonarQube Scanner CLI
    - name: Install SonarQube Scanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
        unzip sonar-scanner-cli-6.2.1.4610-linux-x64.zip
        echo "export PATH=$PWD/sonar-scanner-6.2.1.4610-linux-x64/bin:$PATH" >> $GITHUB_ENV

    # Run SonarQube analysis
    - name: Run SonarQube Scanner
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
        -Dsonar.projectKey=my_project_key \
        -Dsonar.organization=my_organization \
        -Dsonar.sources=. \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      continue-on-error: true

    # Quality Gate status check
    - name: Quality Gate Check
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        PROJECT_STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=my_project_key" | jq -r '.projectStatus.status')
        echo "Quality Gate Status: $PROJECT_STATUS"
        if [ "$PROJECT_STATUS" != "OK" ]; then
          echo "Quality Gate failed. Stopping the pipeline."
          exit 1
        fi
      continue-on-error: true

  build-and-test:
    
    needs: sast
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        cd src 
        docker build . --file Dockerfile --tag ghcr.io/gobamm/msc-bcp-register-api:latest
#        docker build . --file Dockerfile --tag ghcr.io/bcp-dev-team/msc-bcp-register-api:$(date +%s)
##        docker tag ghcr.io/bcp-dev-team/msc-bcp-register-api:$(date +%s) ghcr.io/bcp-dev-team/msc-bcp-register-api:latest

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.ORG_PAT }}

   # Push the Docker image
    - name: Push Docker image
      run: docker push ghcr.io/gobamm/msc-bcp-register-api:latest


  deploy-dev:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - uses: actions/checkout@v4
    
     # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Use kubelogin to configure your kubeconfig for Azure auth
    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
       kubelogin-version: 'v0.0.25'

    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ vars.RESOURCE_GROUP }}
        cluster-name: ${{ vars.CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'

    # Runs Kustomize to create manifest files
    - name: Bake deployment
      uses: azure/k8s-bake@v3
      with:
        renderEngine: "kustomize"
        kustomizationPath: ${{ vars.KUSTOMIZE_PATH }}
        kubectl-version: latest
      id: bake

    # Deploys application based on manifest files from previous step
    - name: Deploy application
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        namespace: bcp-register
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
  

  deploy-uat:
    if: github.event_name == 'pull_request' && github.base_ref == 'release'
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: UAT

    steps:
    - uses: actions/checkout@v4
    
    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v2
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Use kubelogin to configure your kubeconfig for Azure auth
    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
       kubelogin-version: 'v0.0.25'

    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ vars.RESOURCE_GROUP }}
        cluster-name: ${{ vars.CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'

    # Runs Kustomize to create manifest files
    - name: Bake deployment
      uses: azure/k8s-bake@v3
      with:
        renderEngine: "kustomize"
        kustomizationPath: ${{ vars.KUSTOMIZE_PATH }}
        kubectl-version: latest
      id: bake

    # Deploys application based on manifest files from previous step
    - name: Deploy application
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        namespace: bcp-register
        manifests: ${{ steps.bake.outputs.manifestsBundle }}

  dast-and-test-dev:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Run API Tests in DEV
        run: |
          newman run postman_collection.json --environment postman_dev.json --reporters cli
        continue-on-error: true

      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ vars.TARGET_URL }}
          artifact_name: zap-report.html
        continue-on-error: true
      
      - name: Notify Team of DAST Results
        if: failure()
        run: echo "Send email or Microsoft Teams notification for DAST failure."

  dast-and-test-uat:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: UAT

    steps:
      - name: Run API Tests in UAT
        run: |
          newman run postman_collection.json --environment postman_uat.json --reporters cli
        continue-on-error: true

      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ vars.TARGET_URL }}
          artifact_name: zap-report.html
        continue-on-error: true
      
      - name: Notify Team of DAST Results
        if: failure()
        run: echo "Send email or Microsoft Teams notification for DAST failure."

  deploy-prod:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: Production

    steps:
      - uses: actions/checkout@v4
    
      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.RESOURCE_GROUP }}
          cluster-name: ${{ vars.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      # Runs Kustomize to create manifest files
      - name: Bake deployment
        uses: azure/k8s-bake@v3
        with:
          renderEngine: "kustomize"
          kustomizationPath: ${{ vars.KUSTOMIZE_PATH }}
          kubectl-version: latest
        id: bake

      # Deploys application based on manifest files from previous step
      - name: Deploy application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          namespace: bcp-register
          manifests: ${{ steps.bake.outputs.manifestsBundle }}

  dast-and-test-prod:
    needs: deploy-prod
    runs-on: ubuntu-latest
    environment: Production
        
    steps:
      - name: Run API Tests in UAT
        run: |
          newman run postman_collection.json --environment postman_uat.json --reporters cli
        continue-on-error: true
        
      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ vars.TARGET_URL }}
          artifact_name: zap-report.html
        continue-on-error: true
              
      - name: Notify Team of DAST Results
        if: failure()
        run: echo "Send email or Microsoft Teams notification for DAST failure."
        