name: Docker Image CI

env:
  CLUSTER_NAME: "bcp-devsecops-dev"
#  KUSTOMIZE_PATH: "./kustomize"
  RESOURCE_GROUP: "DevSecOps-Dev"

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:

#  build-image:

#    runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v4
#    - name: Build the Docker image
#      run: |
#        cd src 
#        docker build . --file Dockerfile --tag ghcr.io/gobamm/msc-bcp-register-api:latest
##        docker build . --file Dockerfile --tag ghcr.io/bcp-dev-team/msc-bcp-register-api:$(date +%s)
##        docker tag ghcr.io/bcp-dev-team/msc-bcp-register-api:$(date +%s) ghcr.io/bcp-dev-team/msc-bcp-register-api:latest

#    # Log in to GitHub Container Registry
#    - name: Log in to GitHub Container Registry
#      uses: docker/login-action@v2
#      with:
#       registry: ghcr.io
#       username: ${{ github.actor }}
#       password: ${{ secrets.GITHUB_TOKEN }}

#   # Push the Docker image
#    - name: Push Docker image
#      run: docker push ghcr.io/gobamm/msc-bcp-register-api:latest


  deploy:
    runs-on: ubuntu-latest

    steps:
     # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Use kubelogin to configure your kubeconfig for Azure auth
    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
       kubelogin-version: 'v0.0.25'

    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'

    # Runs Kustomize to create manifest files
    - name: Bake deployment
      uses: azure/k8s-bake@v2
      with:
        renderEngine: "kustomize"
        kustomizationPath: ${{ env.KUSTOMIZE_PATH }}
        kubectl-version: latest
      id: bake

    # Deploys application based on manifest files from previous step
    - name: Deploy application
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: ${{ steps.bake.outputs.manifestsBundle }}

